name: Publish Snapshot
on:
  push:
    branches: [main]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Import GPG key
        run: |
          echo "$PGP_SECRET" | base64 -d | gpg --batch --import
          gpg --list-secret-keys
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}

      - uses: sbt/setup-sbt@v1
      - run: sbt publishSigned
        env:
          PGP_PASSPHRASE: ""
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
